id: P008193
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:07:11.918772
source_metadata:
  id: bdr:W1CZ1034
  title: འགྲོ་མགོན་འཕགས་པ་བློ་གྲོས་རྒྱལ་མཚན་གྱི་གསུང་འབུམ་པོད་གསུམ་པ
  author: ''
  volumes:
    10573fa5a32f4bdc86fb9678df96e510:
      image_group_id: I1CZ2141
      title: ''
      volume_number: 1
      total_pages: 1016
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
